/**
 * PrepPulse application tables.
 *
 * Auth-owned tables (users/sessions/accounts/verifications) live in
 * `auth-schema.ts`, which is generated by the Better Auth CLI — keeping them
 * in a separate file means regenerating them never clobbers this one.
 */
import { relations, sql } from "drizzle-orm";
import {
  boolean,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import type { EvaluationPayload, FillerHit, ResumeExtract, Scores } from "@/lib/types";
import { users } from "./auth-schema";

export const practiceModeEnum = pgEnum("practice_mode", [
  "random_topic",
  "interview",
  "group_discussion",
  "debate",
  "conversation",
  "scenario",
]);

export const sessionStatusEnum = pgEnum("session_status", [
  "created",
  "in_progress",
  "completed",
  "abandoned",
]);

export const difficultyEnum = pgEnum("difficulty", ["easy", "medium", "hard"]);

export const languageEnum = pgEnum("language", ["en", "hinglish", "hi"]);

export const aiProviderEnum = pgEnum("ai_provider", ["groq", "gemini"]);

/* ── topics ────────────────────────────────────────────────────────────────
 * Deliberately wide-ranging subject matter — philosophy, science, culture,
 * everyday dilemmas — not just career/GD prompts. See src/db/topics.ts.
 */
export const topics = pgTable(
  "topics",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    category: text("category").notNull(),
    difficulty: difficultyEnum("difficulty").notNull().default("medium"),
    promptText: text("prompt_text").notNull(),
    /** Short AI-generated angle-opener, cached so we don't re-bill for it. */
    cachedBrief: text("cached_brief"),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("topics_prompt_text_unique").on(table.promptText),
    index("topics_category_idx").on(table.category),
  ],
);

/* ── practice_sessions ─────────────────────────────────────────────────── */
export const practiceSessions = pgTable(
  "practice_sessions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    topicId: uuid("topic_id").references(() => topics.id, { onDelete: "set null" }),
    mode: practiceModeEnum("mode").notNull(),
    status: sessionStatusEnum("status").notNull().default("created"),
    language: languageEnum("language").notNull().default("en"),
    /** Denormalised so a session still reads correctly if a topic is retired. */
    promptSnapshot: text("prompt_snapshot"),
    durationSeconds: integer("duration_seconds"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (table) => [
    index("practice_sessions_user_idx").on(table.userId, table.createdAt),
    index("practice_sessions_status_idx").on(table.status),
  ],
);

/* ── evaluations ───────────────────────────────────────────────────────── */
export const evaluations = pgTable(
  "evaluations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sessionId: uuid("session_id")
      .notNull()
      .references(() => practiceSessions.id, { onDelete: "cascade" }),
    scores: jsonb("scores").$type<Scores>().notNull(),
    /** Weighted composite — computed in our code, never taken from the model. */
    overallScore: integer("overall_score").notNull(),
    strengths: jsonb("strengths").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    improvements: jsonb("improvements").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    fillerWords: jsonb("filler_words").$type<FillerHit[]>().notNull().default(sql`'[]'::jsonb`),
    transcript: text("transcript").notNull(),
    improvedAnswer: text("improved_answer"),
    summary: text("summary"),
    wordCount: integer("word_count"),
    wordsPerMinute: integer("words_per_minute"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("evaluations_session_unique").on(table.sessionId)],
);

/* ── profiles ──────────────────────────────────────────────────────────── */
export const profiles = pgTable(
  "profiles",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** Either user-written or distilled from an uploaded resume (Phase 3). */
    skillsDescription: text("skills_description"),
    /** Structured JSON only — the uploaded PDF itself is never stored. */
    resumeExtractedData: jsonb("resume_extracted_data").$type<ResumeExtract>(),
    resumeUpdatedAt: timestamp("resume_updated_at", { withTimezone: true }),
    preferredLanguage: languageEnum("preferred_language").notNull().default("en"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("profiles_user_unique").on(table.userId)],
);

/* ── ai_usage ──────────────────────────────────────────────────────────────
 * Written on every LLM call. Two jobs:
 *   1. Phase 8 cost tracking.
 *   2. The rate limiter counts rows here, so per-user caps need no extra table.
 */
export const aiUsage = pgTable(
  "ai_usage",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id").references(() => users.id, { onDelete: "set null" }),
    sessionId: uuid("session_id").references(() => practiceSessions.id, { onDelete: "set null" }),
    provider: aiProviderEnum("provider").notNull(),
    model: text("model").notNull(),
    operation: text("operation").notNull(),
    inputTokens: integer("input_tokens").notNull().default(0),
    outputTokens: integer("output_tokens").notNull().default(0),
    /** USD, 6dp. Estimated from a local price table — providers bill separately. */
    estimatedCost: numeric("estimated_cost", { precision: 12, scale: 6 }).notNull().default("0"),
    latencyMs: integer("latency_ms"),
    ok: boolean("ok").notNull().default(true),
    errorCode: text("error_code"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("ai_usage_user_time_idx").on(table.userId, table.createdAt),
    index("ai_usage_created_idx").on(table.createdAt),
  ],
);

/* ── streaks ───────────────────────────────────────────────────────────── */
export const streaks = pgTable(
  "streaks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    currentStreak: integer("current_streak").notNull().default(0),
    longestStreak: integer("longest_streak").notNull().default(0),
    /** Plain date, not timestamp — "did they practise today" is a calendar question. */
    lastPracticeDate: date("last_practice_date"),
    tokens: integer("tokens").notNull().default(0),
    totalSessions: integer("total_sessions").notNull().default(0),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("streaks_user_unique").on(table.userId)],
);

/* ── relations ─────────────────────────────────────────────────────────── */
export const practiceSessionsRelations = relations(practiceSessions, ({ one }) => ({
  topic: one(topics, { fields: [practiceSessions.topicId], references: [topics.id] }),
  user: one(users, { fields: [practiceSessions.userId], references: [users.id] }),
  evaluation: one(evaluations, {
    fields: [practiceSessions.id],
    references: [evaluations.sessionId],
  }),
}));

export const evaluationsRelations = relations(evaluations, ({ one }) => ({
  session: one(practiceSessions, {
    fields: [evaluations.sessionId],
    references: [practiceSessions.id],
  }),
}));

export const profilesRelations = relations(profiles, ({ one }) => ({
  user: one(users, { fields: [profiles.userId], references: [users.id] }),
}));

export const streaksRelations = relations(streaks, ({ one }) => ({
  user: one(users, { fields: [streaks.userId], references: [users.id] }),
}));

export type Topic = typeof topics.$inferSelect;
export type PracticeSession = typeof practiceSessions.$inferSelect;
export type Evaluation = typeof evaluations.$inferSelect;
export type Profile = typeof profiles.$inferSelect;
export type Streak = typeof streaks.$inferSelect;
export type AiUsageRow = typeof aiUsage.$inferSelect;
export type { EvaluationPayload };
