/**
 * PrepPulse application tables.
 *
 * Auth-owned tables (users/sessions/accounts/verifications) live in
 * `auth-schema.ts`, which is generated by the Better Auth CLI — keeping them
 * in a separate file means regenerating them never clobbers this one.
 */
import { relations, sql } from "drizzle-orm";
import {
  boolean,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import type {
  AnswerScores,
  EvaluationPayload,
  FillerHit,
  ResumeExtract,
  Scores,
  SessionConfig,
} from "@/lib/types";
import { users } from "./auth-schema";

export const practiceModeEnum = pgEnum("practice_mode", [
  "random_topic",
  "interview",
  "group_discussion",
  "debate",
  "conversation",
  "scenario",
]);

export const sessionStatusEnum = pgEnum("session_status", [
  "created",
  "in_progress",
  "completed",
  "abandoned",
]);

export const difficultyEnum = pgEnum("difficulty", ["easy", "medium", "hard"]);

export const languageEnum = pgEnum("language", ["en", "hinglish", "hi"]);

export const aiProviderEnum = pgEnum("ai_provider", ["groq", "gemini"]);

/** How the answer reached us. Typed answers have no measurable speaking pace. */
export const inputModeEnum = pgEnum("input_mode", ["speech", "typed"]);

/** Interviewer temperament. Changes the system prompt, not the scoring. */
export const personaEnum = pgEnum("interviewer_persona", [
  "friendly",
  "professional",
  "challenging",
  "stress",
]);

export const questionKindEnum = pgEnum("question_kind", [
  "behavioural",
  "technical",
  "situational",
  "motivational",
]);

/* ── topics ────────────────────────────────────────────────────────────────
 * Deliberately wide-ranging subject matter — philosophy, science, culture,
 * everyday dilemmas — not just career/GD prompts. See src/db/topics.ts.
 */
export const topics = pgTable(
  "topics",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    category: text("category").notNull(),
    difficulty: difficultyEnum("difficulty").notNull().default("medium"),
    promptText: text("prompt_text").notNull(),
    /** Deep context on the topic for the user to read before speaking. */
    knowledgeBase: text("knowledge_base"),
    /** Short AI-generated angle-opener, cached so we don't re-bill for it. */
    cachedBrief: text("cached_brief"),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("topics_prompt_text_unique").on(table.promptText),
    index("topics_category_idx").on(table.category),
  ],
);

/* ── practice_sessions ─────────────────────────────────────────────────── */
export const practiceSessions = pgTable(
  "practice_sessions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    topicId: uuid("topic_id").references(() => topics.id, { onDelete: "set null" }),
    mode: practiceModeEnum("mode").notNull(),
    status: sessionStatusEnum("status").notNull().default("created"),
    language: languageEnum("language").notNull().default("en"),
    /**
     * Mode-specific settings in one column rather than a nullable column per
     * mode: persona and question count for interviews, stance and personas for
     * debate. Modes that need nothing store nothing.
     */
    config: jsonb("config").$type<SessionConfig>(),
    /** Denormalised so a session still reads correctly if a topic is retired. */
    promptSnapshot: text("prompt_snapshot"),
    /**
     * Sharing is opt-in and off by default. The slug is separate from the id
     * so revoking a share is a slug change, not a session deletion, and so a
     * shared URL can never be reverse-engineered from a session id.
     */
    shareSlug: text("share_slug").unique(),
    sharedAt: timestamp("shared_at", { withTimezone: true }),
    durationSeconds: integer("duration_seconds"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (table) => [
    index("practice_sessions_user_idx").on(table.userId, table.createdAt),
    index("practice_sessions_status_idx").on(table.status),
  ],
);

/* ── evaluations ───────────────────────────────────────────────────────── */
export const evaluations = pgTable(
  "evaluations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sessionId: uuid("session_id")
      .notNull()
      .references(() => practiceSessions.id, { onDelete: "cascade" }),
    scores: jsonb("scores").$type<Scores>().notNull(),
    /** Weighted composite — computed in our code, never taken from the model. */
    overallScore: integer("overall_score").notNull(),
    strengths: jsonb("strengths").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    improvements: jsonb("improvements").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    fillerWords: jsonb("filler_words").$type<FillerHit[]>().notNull().default(sql`'[]'::jsonb`),
    transcript: text("transcript").notNull(),
    improvedAnswer: text("improved_answer"),
    summary: text("summary"),
    wordCount: integer("word_count"),
    wordsPerMinute: integer("words_per_minute"),
    inputMode: inputModeEnum("input_mode").notNull().default("speech"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("evaluations_session_unique").on(table.sessionId)],
);

/* ── profiles ──────────────────────────────────────────────────────────── */
export const profiles = pgTable(
  "profiles",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    username: text("username"),
    age: integer("age"),
    onboardingCompleted: boolean("onboarding_completed").notNull().default(false),
    /** Either user-written or distilled from an uploaded resume (Phase 3). */
    skillsDescription: text("skills_description"),
    /** Structured JSON only — the uploaded PDF itself is never stored. */
    resumeExtractedData: jsonb("resume_extracted_data").$type<ResumeExtract>(),
    resumeUpdatedAt: timestamp("resume_updated_at", { withTimezone: true }),
    preferredLanguage: languageEnum("preferred_language").notNull().default("en"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("profiles_user_unique").on(table.userId),
    uniqueIndex("profiles_username_unique").on(table.username),
  ],
);

/* ── ai_usage ──────────────────────────────────────────────────────────────
 * Written on every LLM call. Two jobs:
 *   1. Phase 8 cost tracking.
 *   2. The rate limiter counts rows here, so per-user caps need no extra table.
 */
export const aiUsage = pgTable(
  "ai_usage",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id").references(() => users.id, { onDelete: "set null" }),
    sessionId: uuid("session_id").references(() => practiceSessions.id, { onDelete: "set null" }),
    provider: aiProviderEnum("provider").notNull(),
    model: text("model").notNull(),
    operation: text("operation").notNull(),
    inputTokens: integer("input_tokens").notNull().default(0),
    outputTokens: integer("output_tokens").notNull().default(0),
    /** USD, 6dp. Estimated from a local price table — providers bill separately. */
    estimatedCost: numeric("estimated_cost", { precision: 12, scale: 6 }).notNull().default("0"),
    latencyMs: integer("latency_ms"),
    ok: boolean("ok").notNull().default(true),
    errorCode: text("error_code"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("ai_usage_user_time_idx").on(table.userId, table.createdAt),
    index("ai_usage_created_idx").on(table.createdAt),
  ],
);

/* ── streaks ───────────────────────────────────────────────────────────── */
export const streaks = pgTable(
  "streaks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    currentStreak: integer("current_streak").notNull().default(0),
    longestStreak: integer("longest_streak").notNull().default(0),
    /** Plain date, not timestamp — "did they practise today" is a calendar question. */
    lastPracticeDate: date("last_practice_date"),
    tokens: integer("tokens").notNull().default(0),
    totalSessions: integer("total_sessions").notNull().default(0),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("streaks_user_unique").on(table.userId)],
);

/* ── interview_questions ───────────────────────────────────────────────────
 * The whole set is generated once, upfront, and stored. Generating question
 * N+1 after seeing answer N would make the interview un-resumable and would
 * let the model drift toward whatever the candidate happens to be good at.
 */
export const interviewQuestions = pgTable(
  "interview_questions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sessionId: uuid("session_id")
      .notNull()
      .references(() => practiceSessions.id, { onDelete: "cascade" }),
    position: integer("position").notNull(),
    question: text("question").notNull(),
    kind: questionKindEnum("kind").notNull().default("behavioural"),
    /** Why this question was chosen for this candidate — shown in the report. */
    rationale: text("rationale"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("interview_questions_slot_unique").on(table.sessionId, table.position)],
);

/* ── interview_answers ─────────────────────────────────────────────────────
 * One row per attempt, not per question: a retry keeps the original so the
 * report can show the score delta between the two.
 */
export const interviewAnswers = pgTable(
  "interview_answers",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    questionId: uuid("question_id")
      .notNull()
      .references(() => interviewQuestions.id, { onDelete: "cascade" }),
    sessionId: uuid("session_id")
      .notNull()
      .references(() => practiceSessions.id, { onDelete: "cascade" }),
    attempt: integer("attempt").notNull().default(1),
    transcript: text("transcript").notNull(),
    inputMode: inputModeEnum("input_mode").notNull().default("speech"),
    /** content / clarity / relevance / structure, 0-100 each. */
    scores: jsonb("scores").$type<AnswerScores>().notNull(),
    overallScore: integer("overall_score").notNull(),
    feedback: text("feedback").notNull(),
    strengths: jsonb("strengths").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    improvements: jsonb("improvements").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    /** STAR-shaped model answer for behavioural questions. */
    idealAnswer: text("ideal_answer"),
    durationSeconds: integer("duration_seconds"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("interview_answers_session_idx").on(table.sessionId),
    uniqueIndex("interview_answers_attempt_unique").on(table.questionId, table.attempt),
  ],
);

/* ── discussion_turns ──────────────────────────────────────────────────────
 * Every utterance in a group discussion or debate, from the user and from each
 * AI persona, in order. GD metrics are computed from these rows rather than
 * asked of a model, for the same reason pace and filler are counted in code.
 */
export const discussionTurns = pgTable(
  "discussion_turns",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sessionId: uuid("session_id")
      .notNull()
      .references(() => practiceSessions.id, { onDelete: "cascade" }),
    position: integer("position").notNull(),
    /** null speaker = the user; otherwise the persona's id. */
    speaker: text("speaker"),
    role: text("role").notNull(),
    content: text("content").notNull(),
    /** Debate structure: opening / argument / rebuttal / closing. */
    stage: text("stage"),
    /** Whether this turn directly answered the previous speaker. */
    isRebuttal: boolean("is_rebuttal").notNull().default(false),
    wordCount: integer("word_count").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("discussion_turns_slot_unique").on(table.sessionId, table.position)],
);

/* ── plans (Phase 6) ───────────────────────────────────────────────────────
 * Prices and limits live in the database, never in the code. Changing a price
 * must not require a deploy, and a hardcoded price is the thing that ends up
 * disagreeing with the checkout screen.
 */
export const plans = pgTable("plans", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  tagline: text("tagline").notNull(),
  /** Minor units (paise/cents) - never a float for money. */
  priceMonthly: integer("price_monthly").notNull().default(0),
  currency: text("currency").notNull().default("INR"),
  features: jsonb("features").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  /** null means unlimited. */
  dailySessionLimit: integer("daily_session_limit"),
  /** Modes this plan unlocks beyond the free set. */
  unlockedModes: jsonb("unlocked_modes").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  isActive: boolean("is_active").notNull().default(true),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const subscriptionStatusEnum = pgEnum("subscription_status", [
  "active",
  "cancelled",
  "expired",
]);

/* ── subscriptions ─────────────────────────────────────────────────────────
 * Deliberately shaped like a real gateway's data even though checkout is a
 * dummy: provider, provider_ref and a period end. Swapping in Stripe or
 * Razorpay later becomes a change to one component plus a webhook, not a
 * schema migration.
 */
export const subscriptions = pgTable(
  "subscriptions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    planId: uuid("plan_id")
      .notNull()
      .references(() => plans.id, { onDelete: "restrict" }),
    status: subscriptionStatusEnum("status").notNull().default("active"),
    provider: text("provider").notNull().default("dummy"),
    providerRef: text("provider_ref"),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
    currentPeriodEnd: timestamp("current_period_end", { withTimezone: true }),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("subscriptions_user_idx").on(table.userId, table.status)],
);

/* ── relations ─────────────────────────────────────────────────────────── */
export const practiceSessionsRelations = relations(practiceSessions, ({ one }) => ({
  topic: one(topics, { fields: [practiceSessions.topicId], references: [topics.id] }),
  user: one(users, { fields: [practiceSessions.userId], references: [users.id] }),
  evaluation: one(evaluations, {
    fields: [practiceSessions.id],
    references: [evaluations.sessionId],
  }),
}));

export const evaluationsRelations = relations(evaluations, ({ one }) => ({
  session: one(practiceSessions, {
    fields: [evaluations.sessionId],
    references: [practiceSessions.id],
  }),
}));

export const profilesRelations = relations(profiles, ({ one }) => ({
  user: one(users, { fields: [profiles.userId], references: [users.id] }),
}));

export const streaksRelations = relations(streaks, ({ one }) => ({
  user: one(users, { fields: [streaks.userId], references: [users.id] }),
}));

export type InterviewQuestion = typeof interviewQuestions.$inferSelect;
export type InterviewAnswer = typeof interviewAnswers.$inferSelect;
export type DiscussionTurn = typeof discussionTurns.$inferSelect;
export type Plan = typeof plans.$inferSelect;
export type Subscription = typeof subscriptions.$inferSelect;
export type Topic = typeof topics.$inferSelect;
export type PracticeSession = typeof practiceSessions.$inferSelect;
export type Evaluation = typeof evaluations.$inferSelect;
export type Profile = typeof profiles.$inferSelect;
export type Streak = typeof streaks.$inferSelect;
export type AiUsageRow = typeof aiUsage.$inferSelect;
export type { EvaluationPayload };
